diffusion_data:
  dataset: AAPMDR
  root: data/RDDM/50view/
  image_size: 512
  num_channels: 1
  img_to_img_translation: True
  centered: True 
  norm_type: Increase_tenfold   #globe_norm   ,   single_norm,   no_norm,Increase_tenfold
  scale_factor: 10

diffusion_training:
  batch_size: 1
  epochs: 1001
  log_freq: 300 # 多少个step 在命令台info一次
  eval_freq: 50 # 多少个epoch保存一个检查点
  eval_freq_sampling: 50 #多少个epoch采样一次
  condition: Ture #是否条件输入
  input_condition: False #第二个条件
  input_condition_mask: False #第二个或三个条件（掩码）
  condition_type: 1
  objective: 'pred_res'  # 目标函数类型
  test_res_or_noise: "res"  # 测试时预测残差或噪声
  gradient_accumulate_every: 2 # 梯度累积步数
  sum_scale: 1
  fp16: False
  isamp: False
  crop_patch: False
  ema_update_every: 10
  split_batches: False
  sub_dir: False

diffusion_eval:
  batch_size: 1
  pre_model:  check/RDDM/L067/model-800.pt
  only_save_last: True


diffusion_model:
  dim_mults: [1,2,4,8] 
  num_scales: 1000
  ema_rate: 0.999
  dim: 32
  num_unet: 1
  loss_type: l1
  init_dim: null
  out_dim: null
  self_condition: False
  resnet_block_groups: 8
  learned_variance: False
  learned_sinusoidal_cond: False
  random_fourier_features: False
  learned_sinusoidal_dim: 16
  ddim_sampling_eta: 0


diffusion_optim:
  lr: 2.0e-4

